var data_head = [
    "#",
    " Organization Name ",
    " Number of Employees ",
    " Industries ",
    " Headquarters Location ",
    " Description ",
    " CB Rank (Company) ",
    " Estimated Revenue Range ",
    " Investor Type ",
    " Investment Stage ",
    " Funding Status ",
    " Last Funding Date ",
    " Last Funding Amount ",
    " Last Funding Type ",
    " Last Equity Funding Amount ",
    " Last Equity Funding Type ",
    " Total Equity Funding Amount ",
    " Total Funding Amount ",
    " Add Column "
];

var data1 = [
    [
        " ",
        " 1.  Luko ",
        "11-50",
        " Artificial Intelligence, Insurance, InsurTech, Internet of Things, Smart Home",
        " Paris, Ile-de-France, France",
        "Luko is a neo-insurance company that provides home insurance and security technology.",
        "616",
        "Less than $1M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Dec 7, 2020",
        "€50,000,000",
        "Series B",
        "€50,000,000",
        "Series B",
        "$85,099,777",
        "$85,099,777",
        ""
    ],
    [
        " ",
        " 2.  DeadHappy ",
        "11-50",
        " Finance, Financial Services, FinTech, Insurance, InsurTech",
        " Leicester, Leicester, United Kingdom",
        "DeadHappy is an insurtech company that provides digital pay-as-you-go life insurance services.",
        "1,718",
        "$1M to $10M",
        " —\n",
        " —\n",
        "—",
        "Dec 19, 2021",
        "£5,340,604",
        "Equity Crowdfunding",
        "£5,340,604",
        "Equity Crowdfunding",
        "$21,566,655",
        "$21,566,655",
        ""
    ],
    [
        " ",
        " 3.  InsurePay ",
        "11-50",
        " InsurTech",
        " Jupiter, Florida, United States",
        "InsurePay is a workers' compensation administration and insurance premium billing platform for insurance providers.",
        "1,855",
        "Less than $1M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Jan 11, 2022",
        "—",
        "Series B",
        "—",
        "Series B",
        "$5,000,000",
        "$5,000,000",
        ""
    ],
    [
        " ",
        " 4.  Zing Health ",
        "11-50",
        " Health Care, Health Insurance, InsurTech",
        " Chicago, Illinois, United States",
        "Zing Health is a developer of insurance technology used to solve traditional underserved existing healthcare plans.",
        "2,394",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Private Equity",
        "Dec 16, 2021",
        "$25,000,000",
        "Private Equity",
        "$25,000,000",
        "Private Equity",
        "$25,000,000",
        "$25,000,000",
        ""
    ],
    [
        " ",
        " 5.  Slide ",
        "11-50",
        " Financial Services, Insurance, InsurTech, Property Insurance",
        " Tampa, Florida, United States",
        "Slide is a full-stack insurtech that makes it easy for modern consumers to choose the right coverage for their unique needs and budgets.",
        "3,689",
        "—",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Nov 22, 2021",
        "$100,000,000",
        "Series A",
        "$100,000,000",
        "Series A",
        "$100,000,000",
        "$100,000,000",
        ""
    ],
    [
        " ",
        " 6.  Circulo Health ",
        "11-50",
        " Health Care, Insurance, InsurTech",
        " Columbus, Ohio, United States",
        "Circulo Health is a Medicaid insurance company of the future, providing tech-enabled care to the sickest and poorest populations.",
        "4,287",
        "—",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Feb 19, 2021",
        "$50,000,000",
        "Series A",
        "$50,000,000",
        "Series A",
        "$50,000,000",
        "$50,000,000",
        ""
    ],
    [
        " ",
        " 7.  Coterie Insurance ",
        "11-50",
        " Commercial Insurance, Developer APIs, Insurance, InsurTech",
        " Cincinnati, Ohio, United States",
        "Coterie Insurance is an insurtech company that provides an API-based approach to commercial insurance.",
        "4,436",
        "Less than $1M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Oct 26, 2021",
        "$50,000,000",
        "Series B",
        "$50,000,000",
        "Series B",
        "$70,000,000",
        "$70,000,000",
        ""
    ],
    [
        " ",
        " 8.  Tomorrow Ideas ",
        "11-50",
        " Apps, FinTech, Insurance, InsurTech, Legal, Mobile Apps, Software",
        " Seattle, Washington, United States",
        "Tomorrow Ideas develops an application that helps in protecting family’s financial future.",
        "4,444",
        "$1M to $10M",
        " —\n",
        " —\n",
        "M&A",
        "Nov 1, 2019",
        "$9,000,000",
        "Venture - Series Unknown",
        "$9,000,000",
        "Venture - Series Unknown",
        "$22,321,954",
        "$22,321,954",
        ""
    ],
    [
        " ",
        " 9.  Five Sigma ",
        "11-50",
        " B2B, Insurance, InsurTech, Productivity Tools, SaaS",
        " Tel Aviv, Tel Aviv, Israel",
        "Five Sigma is a B2B insurtech start-up selling SaaS claims management systems to help carriers transform their claims management process.",
        "5,316",
        "—",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Jan 19, 2022",
        "$2,000,000",
        "Series A",
        "$2,000,000",
        "Series A",
        "$20,000,000",
        "$20,000,000",
        ""
    ],
    [
        " ",
        " 10.  Jones ",
        "11-50",
        " InsurTech, Property Management, Real Estate, Software",
        " New York, New York, United States",
        "Jones offers independent contractors a Pay-As-You-Go solution to end the hassle of liability insurance.",
        "5,455",
        "Less than $1M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Jul 19, 2021",
        "$12,500,000",
        "Series A",
        "$12,500,000",
        "Series A",
        "$20,500,000",
        "$20,500,000",
        ""
    ],
    [
        " ",
        " 11.  Humn.ai ",
        "11-50",
        " Artificial Intelligence, Auto Insurance, Car Sharing, Commercial Insurance, Data Visualization, InsurTech, Machine Learning",
        " London, England, United Kingdom",
        "Humn.ai develops an insurance platform that delivers risk-adjusted insurance pricing in real time for commercial vehicle fleets.",
        "5,567",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Oct 13, 2021",
        "£10,100,000",
        "Series A",
        "£10,100,000",
        "Series A",
        "$23,147,628",
        "$23,147,628",
        ""
    ],
    [
        " ",
        " 12.  Boost ",
        "11-50",
        " Financial Services, FinTech, Insurance, InsurTech",
        " New York, New York, United States",
        "Boost enables innovators to build, offer, and deliver insurance products to their customers.",
        "5,779",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "May 20, 2021",
        "$20,000,000",
        "Series B",
        "$20,000,000",
        "Series B",
        "$37,000,000",
        "$37,000,000",
        ""
    ],
    [
        " ",
        " 13.  Finsall Resources ",
        "1-10",
        " Financial Services, Insurance, InsurTech",
        " Bengaluru, Karnataka, India",
        "Finsall Resources is a Finsuretech company, financially enabling people to buy (or to buy more) insurance.",
        "5,791",
        "$100M to $500M",
        " —\n",
        " —\n",
        "Seed",
        "Jan 19, 2022",
        "₹120,000,000",
        "Seed",
        "₹120,000,000",
        "Seed",
        "₹144,000,000",
        "₹144,000,000",
        ""
    ],
    [
        " ",
        " 14.  Azos ",
        "1-10",
        " Information Technology, Insurance, InsurTech",
        " São Paulo, Sao Paulo, Brazil",
        "Azos is an insurtech firm that offers personalized insurance services.",
        "5,807",
        "—",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Nov 30, 2021",
        "R$55,000,000",
        "Series A",
        "R$55,000,000",
        "Series A",
        "R$67,850,000",
        "R$67,850,000",
        ""
    ],
    [
        " ",
        " 15.  Vesttoo ",
        "11-50",
        " Artificial Intelligence, Asset Management, Finance, FinTech, Insurance, InsurTech, Machine Learning, Marketplace, Risk Management, Trading Platform",
        " Tel Aviv, Tel Aviv, Israel",
        "Vesttoo is the world’s first marketplace for non-CAT insurance-based risk transfer and investments",
        "6,095",
        "$10M to $50M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Nov 21, 2021",
        "$15,000,000",
        "Series B",
        "$15,000,000",
        "Series B",
        "$23,000,000",
        "$23,000,000",
        ""
    ],
    [
        " ",
        " 16.  Loop ",
        "11-50",
        " Artificial Intelligence, Financial Services, Insurance, InsurTech",
        " Washington, District of Columbia, United States",
        "Loop Insurance uses AI-technology, big data, and telematics to create more fairly priced insurance products.",
        "6,176",
        "—",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Sep 30, 2021",
        "$21,000,000",
        "Series A",
        "$21,000,000",
        "Series A",
        "$24,250,000",
        "$24,250,000",
        ""
    ],
    [
        " ",
        " 17.  Flume Health ",
        "11-50",
        " Financial Services, FinTech, Health Care, Information Technology, InsurTech",
        " New York, New York, United States",
        "Flume Health is a digital TPA helping self-insured employers make their health plans more affordable and easier to use.",
        "6,408",
        "Less than $1M",
        " —\n",
        " —\n",
        "Seed",
        "May 25, 2021",
        "$6,000,000",
        "Seed",
        "$6,000,000",
        "Seed",
        "$10,150,000",
        "$10,150,000",
        ""
    ],
    [
        " ",
        " 18.  Riskcovry ",
        "11-50",
        " Insurance, InsurTech",
        " Bengaluru, Karnataka, India",
        "Riskcovry is an \"Insurance-in-a-box” model offers a one-stop-shop platform to cater to any business's digital insurance needs.",
        "6,445",
        "$10M to $50M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Mar 9, 2021",
        "₹366,000,000",
        "Series A",
        "₹366,000,000",
        "Series A",
        "$5,029,127",
        "$5,029,127",
        ""
    ],
    [
        " ",
        " 19.  OneDegree ",
        "11-50",
        " Financial Services, Insurance, InsurTech",
        " Kwun Tong, Kowloon, Hong Kong",
        "OneDegree is an insurtech company that has digitized the insurance process from end-to-end.",
        "6,714",
        "$100M to $500M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Aug 30, 2021",
        "$28,000,000",
        "Series B",
        "$28,000,000",
        "Series B",
        "$58,000,000",
        "$58,000,000",
        ""
    ],
    [
        " ",
        " 20.  Groundspeed Analytics ",
        "11-50",
        " Analytics, Commercial Insurance, Insurance, InsurTech, Machine Learning",
        " Ann Arbor, Michigan, United States",
        "Groundspeed Analytics accelerates commercial insurance performance with the power of machine learning and artificial intelligence.",
        "6,909",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Late Stage Venture",
        "Jan 6, 2021",
        "—",
        "Series C",
        "—",
        "Series C",
        "$32,000,000",
        "$32,000,000",
        ""
    ],
    [
        " ",
        " 21.  TrustLayer ",
        "11-50",
        " Artificial Intelligence, Insurance, InsurTech, Machine Learning",
        " San Francisco, California, United States",
        "TrustLayer is an insurtech company automating insurance verification with machine learning and AI.",
        "6,985",
        "Less than $1M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Aug 17, 2021",
        "$15,100,000",
        "Series A",
        "$15,100,000",
        "Series A",
        "$21,700,000",
        "$21,700,000",
        ""
    ],
    [
        " ",
        " 22.  Huckleberry ",
        "1-10",
        " Insurance, InsurTech, Internet",
        " San Francisco, California, United States",
        "Huckleberry Insurance Services is a licensed insurance producer, resident",
        "6,992",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Dec 18, 2019",
        "$18,000,000",
        "Series A",
        "$18,000,000",
        "Series A",
        "$22,000,000",
        "$22,000,000",
        ""
    ],
    [
        " ",
        " 23.  Arturo ",
        "11-50",
        " Artificial Intelligence, InsurTech, Machine Learning, Predictive Analytics, Property Management",
        " Chicago, Illinois, United States",
        "Arturo is a deep learning spin-out from a Fortune 500 company focused on delivering highly accurate measurement and predictive data.",
        "7,232",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Apr 27, 2021",
        "$25,000,000",
        "Series B",
        "$25,000,000",
        "Series B",
        "$33,000,000",
        "$33,000,000",
        ""
    ],
    [
        " ",
        " 24.  Glow ",
        "11-50",
        " Apps, Health Care, InsurTech, Internet, Women's",
        " San Francisco, California, United States",
        "Glow is a fertility app that crunches and analyzes vast quantities of data to help users take control of their reproductive health.",
        "7,276",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Oct 2, 2014",
        "$17,000,000",
        "Series B",
        "$17,000,000",
        "Series B",
        "$23,000,000",
        "$23,000,000",
        ""
    ],
    [
        " ",
        " 25.  Mulberry Technology ",
        "11-50",
        " CRM, Customer Service, InsurTech",
        " New York, New York, United States",
        "Mulberry develops personalized product protection solutions used to help brands unlock additional revenue.",
        "7,556",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Oct 13, 2021",
        "$22,000,000",
        "Series B",
        "$22,000,000",
        "Series B",
        "$34,750,000",
        "$34,750,000",
        ""
    ],
    [
        " ",
        " 26.  Flock Ltd. ",
        "11-50",
        " Automotive, Autonomous Vehicles, Big Data, FinTech, Fleet Management, Insurance, InsurTech, Software",
        " London, England, United Kingdom",
        "London-based insurtech building the world's first fully digital insurance company for connected and autonomous commercial vehicles",
        "7,770",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Jul 29, 2021",
        "$17,000,000",
        "Series A",
        "$17,000,000",
        "Series A",
        "$21,212,798",
        "$21,344,133",
        ""
    ],
    [
        " ",
        " 27.  Urban Jungle ",
        "11-50",
        " Financial Services, FinTech, Insurance, InsurTech",
        " London, England, United Kingdom",
        "Urban Jungle provides an insurance technology to help young people get cheaper, better home insurance.",
        "7,899",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Jun 3, 2021",
        "$11,400,000",
        "Series A",
        "$11,400,000",
        "Series A",
        "$22,300,000",
        "$22,300,000",
        ""
    ],
    [
        " ",
        " 28.  Hi Marley ",
        "11-50",
        " Artificial Intelligence, Insurance, InsurTech, Internet of Things, Messaging",
        " Boston, Massachusetts, United States",
        "Hi Marley is a developer of an artificially intelligent-based SMS texting platform designed to bridge the conversation.",
        "8,137",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Mar 11, 2021",
        "$25,000,000",
        "Series B",
        "$25,000,000",
        "Series B",
        "$41,700,000",
        "$41,700,000",
        ""
    ],
    [
        " ",
        " 29.  Foresight Commercial Insurance ",
        "11-50",
        " Commercial Insurance, Information Technology, Insurance, InsurTech, Risk Management",
        " San Francisco, California, United States",
        "Foresight is the commercial insurtech that ties safe work practices to insurance savings.",
        "8,224",
        "—",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Jan 19, 2022",
        "$39,000,000",
        "Series B",
        "$39,000,000",
        "Series B",
        "$58,100,000",
        "$58,100,000",
        ""
    ],
    [
        " ",
        " 30.  Kettle ",
        "11-50",
        " Financial Services, Information Technology, Insurance, InsurTech, Machine Learning",
        " Berkeley, California, United States",
        "Kettle is an insurtech company that develops a machine-learning powered reinsurer balancing risk in a changing climate.",
        "8,255",
        "—",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Nov 18, 2021",
        "$25,000,000",
        "Series A",
        "$25,000,000",
        "Series A",
        "$29,710,000",
        "$29,710,000",
        ""
    ],
    [
        " ",
        " 31.  Tribe Accelerator ",
        "11-50",
        " Automotive, Blockchain, Information Technology, InsurTech, Logistics, Sustainability",
        " Singapore, Central Region, Singapore",
        "The First Singapore Government-Supported Blockchain Accelerator",
        "8,269",
        "—",
        " Accelerator\n",
        " —\n",
        "—",
        "Apr 14, 2021",
        "$70,000,000",
        "Venture - Series Unknown",
        "$70,000,000",
        "Venture - Series Unknown",
        "$85,761,527",
        "$85,761,527",
        ""
    ],
    [
        " ",
        " 32.  Nirvana Health ",
        "1-10",
        " FinTech, Health Care, Health Insurance, Insurance, InsurTech, Wellness",
        " New York, New York, United States",
        "Nirvana Health is a mental health company providing modern fintech and insurance solutions to healthchare.",
        "8,357",
        "—",
        " —\n",
        " —\n",
        "Seed",
        "Nov 16, 2021",
        "$7,500,000",
        "Seed",
        "$7,500,000",
        "Seed",
        "$15,200,000",
        "$15,200,000",
        ""
    ],
    [
        " ",
        " 33.  Unkle ",
        "11-50",
        " Credit, Insurance, InsurTech, Real Estate",
        " Paris, Ile-de-France, France",
        "Unkle is a one-stop-shop insurtech insurance for real estate. Renting made easier",
        "8,381",
        "Less than $1M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Jan 14, 2022",
        "€10,000,000",
        "Series A",
        "€10,000,000",
        "Series A",
        "€11,000,000",
        "€11,000,000",
        ""
    ],
    [
        " ",
        " 34.  Thimble ",
        "11-50",
        " Financial Services, FinTech, Insurance, InsurTech, Mobile",
        " New York, New York, United States",
        "Thimble is an insurance producer enabling small businesses to succeed on their own terms.",
        "8,448",
        "Less than $1M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Oct 15, 2019",
        "$22,000,000",
        "Series A",
        "$22,000,000",
        "Series A",
        "$28,900,000",
        "$28,900,000",
        ""
    ],
    [
        " ",
        " 35.  PolicyStreet ",
        "11-50",
        " Finance, Financial Services, FinTech, Insurance, InsurTech",
        " Kuala Lumpur, Kuala Lumpur, Malaysia",
        "PolicyStreet is an online platform that makes the process of buying insurance more efficient.",
        "8,767",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Sep 28, 2021",
        "MYR25,000,000",
        "Series A",
        "MYR25,000,000",
        "Series A",
        "$9,493,552",
        "$9,528,552",
        ""
    ],
    [
        " ",
        " 36.  Igloo ",
        "11-50",
        " Artificial Intelligence, Financial Services, FinTech, Insurance, InsurTech",
        " Singapore, Central Region, Singapore",
        "Igloo is an insurtech AI platform that provides insurance accessible through creating digital insurance products.",
        "8,883",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Apr 24, 2020",
        "$16,000,000",
        "Series A",
        "$16,000,000",
        "Series A",
        "$16,000,000",
        "$16,000,000",
        ""
    ],
    [
        " ",
        " 37.  DeNexus ",
        "1-10",
        " B2B, Cyber Security, InsurTech, Risk Management, SaaS",
        " Sausalito, California, United States",
        "DeNexus is an industrial cyber-risk modeling and quantification company providing data-driven cyber-risk modeling for industrial networks.",
        "8,898",
        "Less than $1M",
        " —\n",
        " —\n",
        "—",
        "Jan 5, 2022",
        "$9,079,233",
        "Venture - Series Unknown",
        "$9,079,233",
        "Venture - Series Unknown",
        "$15,329,233",
        "$15,329,233",
        ""
    ],
    [
        " ",
        " 38.  Salty. ",
        "11-50",
        " Insurance, InsurTech, SaaS, UX Design",
        " Salt Lake City, Utah, United States",
        "Salty Dot, Inc. is the Embedded Insurance® technology company",
        "8,927",
        "—",
        " —\n",
        " —\n",
        "M&A",
        "Mar 31, 2021",
        "$15,000,000",
        "Venture - Series Unknown",
        "$15,000,000",
        "Venture - Series Unknown",
        "$34,661,854",
        "$34,661,854",
        ""
    ],
    [
        " ",
        " 39.  Cytora ",
        "11-50",
        " Artificial Intelligence, Commercial Insurance, Information Technology, Insurance, InsurTech, Risk Management, Software",
        " London, England, United Kingdom",
        "Cytora is a configurable platform that enables commercial insurers to create digital workflows by digitising, evaluating and routing risks.",
        "9,017",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Apr 16, 2019",
        "£25,000,000",
        "Series B",
        "£25,000,000",
        "Series B",
        "$41,430,336",
        "$41,430,336",
        ""
    ],
    [
        " ",
        " 40.  SafetyWing ",
        "11-50",
        " Apps, Health Insurance, Insurance, InsurTech",
        " Palo Alto, California, United States",
        "SafetyWing is a startup that provides travel medical insurance solutions to remote and gig economy workers.",
        "9,024",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Jan 22, 2021",
        "$8,000,000",
        "Series A",
        "$8,000,000",
        "Series A",
        "$12,120,000",
        "$12,120,000",
        ""
    ],
    [
        " ",
        " 41.  Collective Benefits ",
        "11-50",
        " Financial Services, InsurTech",
        " London, England, United Kingdom",
        "Insurance and benefits to make independent work, work for everyone.",
        "9,321",
        "—",
        " —\n",
        " —\n",
        "—",
        "Nov 3, 2021",
        "£7,300,000",
        "Venture - Series Unknown",
        "£7,300,000",
        "Venture - Series Unknown",
        "£16,600,000",
        "£16,600,000",
        ""
    ],
    [
        " ",
        " 42.  InsuRights ",
        "11-50",
        " Artificial Intelligence, Health Care, InsurTech, Medical",
        " Tel Aviv, Tel Aviv, Israel",
        "Insurights is an AI-powered digital platform that allows employees to utilize their health benefits and coverage.",
        "9,823",
        "—",
        " —\n",
        " —\n",
        "Seed",
        "Oct 19, 2021",
        "$22,000,000",
        "Seed",
        "$22,000,000",
        "Seed",
        "$23,500,000",
        "$23,500,000",
        ""
    ],
    [
        " ",
        " 43.  Protecht ",
        "11-50",
        " FinTech, Fraud Detection, Insurance, InsurTech, Payments, Sales Automation",
        " Phoenix, Arizona, United States",
        "Protecht is an insurtech company that utilizes embedded technologies to distribute insurance products to consumers globally.",
        "10,068",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Jan 5, 2020",
        "$5,000,000",
        "Debt Financing",
        "$5,000,000",
        "Series A",
        "$13,000,000",
        "$21,925,000",
        ""
    ],
    [
        " ",
        " 44.  hi.health ",
        "11-50",
        " FinTech, Health Care, Health Insurance, Information Technology, InsurTech",
        " Vienna, Wien, Austria",
        "hi.health is the contemporary approach to digitally organized personal healthcare.",
        "10,233",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Seed",
        "Jan 17, 2022",
        "—",
        "Convertible Note",
        "$1,000,000",
        "Seed",
        "$1,000,000",
        "$1,000,000",
        ""
    ],
    [
        " ",
        " 45.  Pathpoint ",
        "11-50",
        " Financial Services, Insurance, InsurTech, Software",
        " San Francisco, California, United States",
        "Pathpoint is a provider of digital insurance wholesale brokerage services for carriers.",
        "10,694",
        "—",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Jun 29, 2021",
        "$30,000,000",
        "Series A",
        "$30,000,000",
        "Series A",
        "$30,000,000",
        "$30,000,000",
        ""
    ],
    [
        " ",
        " 46.  Gentem ",
        "1-10",
        " Health Care, InsurTech",
        " San Francisco, California, United States",
        "Gentem develops a medical platform intended to help physicians with instant reimbursements.",
        "10,916",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Feb 9, 2021",
        "$10,000,000",
        "Series A",
        "$10,000,000",
        "Series A",
        "$13,700,000",
        "$13,700,000",
        ""
    ],
    [
        " ",
        " 47.  Obie ",
        "11-50",
        " Commercial Insurance, Commercial Real Estate, Insurance, InsurTech, Real Estate, Real Estate Investment",
        " Chicago, Illinois, United States",
        "Obie is an insurtech startup that offers insurance and risk management for real estate investors.",
        "11,661",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "May 26, 2021",
        "$10,700,000",
        "Series A",
        "$10,700,000",
        "Series A",
        "$13,650,000",
        "$13,650,000",
        ""
    ],
    [
        " ",
        " 48.  Arbol ",
        "1-10",
        " Agriculture, AgTech, Big Data, Insurance, InsurTech, Marketplace",
        " New York, New York, United States",
        "Arbol is an InsurTech platform for parametric products that pay quickly and fairly covering external risks such as unexpected weather.",
        "11,761",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Jan 19, 2021",
        "$7,000,000",
        "Series A",
        "$7,000,000",
        "Series A",
        "$9,000,000",
        "$9,000,000",
        ""
    ],
    [
        " ",
        " 49.  Safesite ",
        "1-10",
        " Enterprise Software, Information Services, Information Technology, InsurTech, Mobile, Risk Management",
        " San Francisco, California, United States",
        "The #1 Way to Put Safety First",
        "12,219",
        "$1M to $10M",
        " —\n",
        " —\n",
        "Early Stage Venture",
        "Dec 20, 2020",
        "$15,000,000",
        "Series A",
        "$15,000,000",
        "Series A",
        "$19,100,000",
        "$19,100,000",
        ""
    ],
    [
        " ",
        " 50.  LiquidX ",
        "11-50",
        " Finance, Financial Services, FinTech, Insurance, InsurTech, Marketplace, Supply Chain Management, Trading Platform",
        " New York, New York, United States",
        "LiquidX operates an electronic exchange platform for the exchange of trade finance assets.",
        "12,247",
        "$10M to $50M",
        " —\n",
        " —\n",
        "—",
        "Nov 2, 2020",
        "$20,999,900",
        "Corporate Round",
        "$20,999,900",
        "Corporate Round",
        "$40,961,900",
        "$40,961,900",
        ""
    ]
];


var  data= [];
var data = data.concat(data1);



