# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Shibu Deb Polo"
email: polodev10@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal Blog 
baseurl: "/shibudebpolo" # the subpath of your site, e.g. /blog
url: "https://polodev.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: polodev/shibudebpolo
twitter: shibudebpolo
github: polodev
header_image: assets/letter_s.jpg
# header_image: assets/profile.jpeg

google_analytics:
comments: true
disqus: daily-dose-2
no_toc: true
toc_min: 2
toc_max: 6
minima:
  date_format: "%b %-d, %Y"


author: Shibu Chandra Debnath
author_bio: >-
  Hey there! 😄 My name is Shibu Chandra Debnath (Polo). I'm a web developer and 
  CTO at https://bimafy.com. Currently reside in Dhaka, 
  Bangladesh. I'm looking to help those that need web development work done, or
  searching for ideas and management for their next content project.
author_pic: https://polodev.github.io/shibu_deb_polo.jpg
paginate: 5
paginate_path: "/:num/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Build settings
theme: null
theme_color: "#1eada9"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
permalink: /:title

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: Shibu Chandra Debnath
      avatar: assets/profile.jpeg
  - scope:
      path: "" # an empty string here means all files in the project
      type: "learning" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: Shibu Chandra Debnath
      avatar: assets/profile.jpeg
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
  - scope:
      path: ""
      type: journals
    values:
      layout: journal-entry
      content-type: journals
  - scope:
      path: ""
      type: statements
    values:
      layout: statement-single
      content-type: statements

# Allows all pages to be put into `_pages` folder
# for easier navigation and better SEO.
collections:
  pages:
    output: true
    permalink: /:title
  notes:
    output: true
    permalink: /notes/:title
  learning:
    output: true
    permalink: /learning/:title
  # journals:
  #   output: true
  #   permalink: /journals/:title
  statements:
    output: true
    permalink: /statements/:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
